"""
Tests for multi-format import support in convert_data.py.

Covers: _SUPPORTED_EXTENSIONS, _read_source dispatcher, _read_xml,
_read_raw_csv, convert_and_save with explicit path, and _find_source_file.
"""

import pathlib
import shutil
import sys
import textwrap

import pandas as pd

ROOT = pathlib.Path(__file__).resolve().parent.parent
FIXTURE = ROOT / "tests" / "fixtures" / "sample_anonymized.xlsx"

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


# ---------------------------------------------------------------------------
# _SUPPORTED_EXTENSIONS
# ---------------------------------------------------------------------------


def test_supported_extensions_constant():
    """All expected extensions must be present in _SUPPORTED_EXTENSIONS."""
    import convert_data

    expected = {".xlsx", ".xls", ".ods", ".xml", ".csv", ".tsv"}
    assert expected <= set(convert_data._SUPPORTED_EXTENSIONS), (
        f"Missing extensions: {expected - set(convert_data._SUPPORTED_EXTENSIONS)}"
    )


# ---------------------------------------------------------------------------
# _read_source dispatcher
# ---------------------------------------------------------------------------


def test_read_source_dispatches_excel():
    """_read_source on the sample xlsx fixture returns a non-empty DataFrame."""
    import convert_data

    df = convert_data._read_source(FIXTURE)
    assert isinstance(df, pd.DataFrame)
    assert len(df) > 0


# ---------------------------------------------------------------------------
# _read_xml
# ---------------------------------------------------------------------------

_FLAT_XML = textwrap.dedent("""\
    <?xml version="1.0" encoding="UTF-8"?>
    <root>
        <item>
            <submitdate>2024-01-01</submitdate>
            <name>Alice</name>
            <score>3</score>
        </item>
        <item>
            <submitdate>2024-01-02</submitdate>
            <name>Bob</name>
            <score>4</score>
        </item>
    </root>
""")

_ROW_XML = textwrap.dedent("""\
    <?xml version="1.0" encoding="UTF-8"?>
    <responses>
        <rows>
            <row>
                <submitdate>2024-01-01</submitdate>
                <name>Carol</name>
                <score>5</score>
            </row>
            <row>
                <submitdate>2024-01-02</submitdate>
                <name>Dave</name>
                <score>2</score>
            </row>
        </rows>
    </responses>
""")


def test_read_xml_flat(tmp_path):
    """_read_xml should parse a simple flat XML into a DataFrame."""
    import convert_data

    xml_file = tmp_path / "flat.xml"
    xml_file.write_text(_FLAT_XML, encoding="utf-8")
    df = convert_data._read_xml(xml_file)
    assert isinstance(df, pd.DataFrame)
    assert len(df) == 2
    assert "name" in df.columns
    assert set(df["name"].tolist()) == {"Alice", "Bob"}


def test_read_xml_row_elements(tmp_path):
    """_read_xml should parse XML with nested <row> elements."""
    import convert_data

    xml_file = tmp_path / "rows.xml"
    xml_file.write_text(_ROW_XML, encoding="utf-8")
    df = convert_data._read_xml(xml_file)
    assert isinstance(df, pd.DataFrame)
    assert len(df) == 2
    assert "name" in df.columns
    assert set(df["name"].tolist()) == {"Carol", "Dave"}


# ---------------------------------------------------------------------------
# _read_raw_csv
# ---------------------------------------------------------------------------

_SIMPLE_CSV = textwrap.dedent("""\
    submitdate,name,score
    2024-01-01,Alice,3
    2024-01-02,Bob,4
""")

_CSV_WITH_METADATA = textwrap.dedent("""\
    Export generated by SurveyTool v2
    Project: ResilienceScan
    submitdate,name,score
    2024-01-01,Alice,3
    2024-01-02,Bob,4
""")


def test_read_raw_csv_utf8(tmp_path):
    """_read_raw_csv should parse a plain UTF-8 CSV correctly."""
    import convert_data

    csv_file = tmp_path / "simple.csv"
    csv_file.write_text(_SIMPLE_CSV, encoding="utf-8")
    df = convert_data._read_raw_csv(csv_file)
    assert isinstance(df, pd.DataFrame)
    assert len(df) == 2
    assert list(df.columns) == ["submitdate", "name", "score"]
    assert set(df["name"].tolist()) == {"Alice", "Bob"}


def test_read_raw_csv_with_header_offset(tmp_path):
    """_read_raw_csv should skip metadata rows before the real header."""
    import convert_data

    csv_file = tmp_path / "with_metadata.csv"
    csv_file.write_text(_CSV_WITH_METADATA, encoding="utf-8")
    df = convert_data._read_raw_csv(csv_file)
    assert isinstance(df, pd.DataFrame)
    assert len(df) == 2
    assert "name" in df.columns
    assert "submitdate" in df.columns


# ---------------------------------------------------------------------------
# convert_and_save with explicit path
# ---------------------------------------------------------------------------


def test_convert_and_save_with_explicit_path(tmp_path, monkeypatch):
    """convert_and_save(path) should convert the fixture and return True."""
    import convert_data

    data_dir = tmp_path / "data"
    data_dir.mkdir()
    dest = data_dir / "sample_anonymized.xlsx"
    shutil.copy(FIXTURE, dest)

    out_csv = data_dir / "cleaned_master.csv"
    monkeypatch.setattr(convert_data, "OUTPUT_PATH", out_csv)
    monkeypatch.setattr(convert_data, "DATA_DIR", data_dir)

    result = convert_data.convert_and_save(dest)
    assert result is True
    assert out_csv.exists()
    df = pd.read_csv(out_csv)
    assert len(df) > 0


# ---------------------------------------------------------------------------
# _find_source_file
# ---------------------------------------------------------------------------


def test_find_source_file_prefers_xlsx(tmp_path):
    """_find_source_file should prefer .xlsx over .xml when both are present."""
    import convert_data

    (tmp_path / "data.xlsx").write_bytes(b"")
    (tmp_path / "data.xml").write_text("<r/>", encoding="utf-8")
    result = convert_data._find_source_file(tmp_path)
    assert result is not None
    assert result.suffix == ".xlsx"


def test_find_source_file_finds_xml(tmp_path):
    """_find_source_file should find an .xml file when no Excel/ODS is present."""
    import convert_data

    xml_file = tmp_path / "data.xml"
    xml_file.write_text("<r/>", encoding="utf-8")
    result = convert_data._find_source_file(tmp_path)
    assert result is not None
    assert result.suffix == ".xml"


def test_find_source_file_returns_none_when_empty(tmp_path):
    """_find_source_file should return None for an empty directory."""
    import convert_data

    result = convert_data._find_source_file(tmp_path)
    assert result is None
